# Generated by Django 4.2.18 on 2025-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
