# Generated by Django 4.2.18 on 2025-01-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='is_side',
            field=models.BooleanField(default=False),
        ),
    ]
