# Generated by Django 4.2.18 on 2025-01-27 15:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_meal_is_main_meal_is_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
