# Generated by Django 4.2.18 on 2025-01-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealselection',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Lunch'), ('dinner', 'Dinner')], default='lunch', max_length=100),
        ),
    ]
